### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by agithubaccountt** [notunixian/abyss-crack#1]
sorry for asking how to run this but friend really wants me to help him 
so what he does he just runs munch with the dll in the mod folder but he doesn't know how to run abyss can somebody help us please? he has astral bypass and there's this thing where there's an abyss key

**Comment by AntiSatan42** [comment]
all you gotta do is put the dll in the mods folder
then it should work munch and abyss don't work for me so try removing munch

**Comment by agithubaccountt** [comment]
thank you we just had to move all other mods in a diff folder
