### ISSUE TITLE
Running Abyss Crashes My Game.

### ISSUE THREAD

**Issue by bakersrule2020** [notunixian/abyss-crack#2]
I Had Trinity Client And Everything But Decided To Try This. Got AstralBypass And AstralCore, The Usual. i launch the game, i get this error.

Fatal Error In GC: Collecting from unknown thread

The Game Halts.
Click Okay? The Game Crashes.

**Comment by notunixian** [comment]
most likely caused by the mods you have installed, remove them and try it
